### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by Kraker01** [vogler/epicgames-claimer#1]
Hi, have followed your instructions  but I am not able to login because I am receiving °incorrect response° error. Userid and password are correct .

**Comment by vogler** [comment]
I noticed the same and used Facebook to login, which worked.
The good thing is that they seem to show a captcha at login whenever it would also show one in the last step of claiming a game, such that the login can be used as a proxy for testing without accidentally claiming and having to wait.
Incognito window in my native Chrome first worked without captcha, then I played around with the script which showed a captcha and now it also shows one in native Chrome incognito mode. So it's also dependent on the IP address.

**Comment by vogler** [comment]
Just logged in with username/password in native Chrome incognito mode with the same IP, so the time they show you a captcha is <6h (prob. much less).

**Comment by Kraker01** [comment]
Linked Facebook to EpicGames outside your script, i got past Incorrect Response error. After logging in, the first browser (the one loading using "npm run login") keeps on refreshing the same page. Closing the browser and running "npm start" gives this error:

> start
> node main.stealth

node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

page.goto: Timeout 10000ms exceeded.
=========================== logs ===========================
navigating to "https://www.epicgames.com/store/en-US/free-games", waiting until "load"
============================================================
    at C:\Users\Marco\Downloads\epicgames-claimer-main\main.stealth.js:73:14 {
  name: 'TimeoutError'

**Comment by vogler** [comment]
> After logging in, the first browser (the one loading using "npm run login") keeps on refreshing the same page.

Can confirm, same for me. Once it starts refreshing, the login was successful.
Can you try the latest commit? I changed it to keep all user data which should make authentication more reliable.

Missed to try headless mode again, but headful it just worked and claimed the current games I did not already have.
Just need to comment that out:
https://github.com/vogler/epicgames-claimer/blob/e34a5fed60fa14b55446a38d28cd0027dc28e773/main.stealth.js#L28

**Comment by Kraker01** [comment]
Thanks, it worked. I'm waiting for this week free game to try redeeming.

**Comment by vogler** [comment]
Ok, I'll close this then. The refreshing after login is not ideal, but maybe that's just their website - I mentioned it in the readme.
